apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: urotaximysqlpvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: urotaxistorageclass  
