apiVersion: v1
kind: PersistentVolume
metadata:
  name: urotaximysqlpv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: urotaxistorageclass
  hostPath:
    path: /u01/data
  